-- MySQL Script generated by MySQL Workbench
-- Sat 25 Dec 2021 06:57:28 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fabrica_picoles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `sabores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabores` ;

CREATE TABLE IF NOT EXISTS `sabores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_embalagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_embalagem` ;

CREATE TABLE IF NOT EXISTS `tipos_embalagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_picole` ;

CREATE TABLE IF NOT EXISTS `tipos_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `picoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `picoles` ;

CREATE TABLE IF NOT EXISTS `picoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(8,2) NOT NULL,
  `id_sabor` INT NOT NULL,
  `id_tipo_embalagem` INT NOT NULL,
  `id_tipo_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picoles_1_idx` (`id_sabor` ASC) VISIBLE,
  INDEX `fk_picoles_2_idx` (`id_tipo_embalagem` ASC) VISIBLE,
  INDEX `fk_picoles_3_idx` (`id_tipo_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingredientes` ;

CREATE TABLE IF NOT EXISTS `ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingredientes_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingredientes_picole` ;

CREATE TABLE IF NOT EXISTS `ingredientes_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ingrediente` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredientes_picole_1_idx` (`id_ingrediente` ASC) VISIBLE,
  INDEX `fk_ingredientes_picole_2_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aditivos_nutritivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aditivos_nutritivos` ;

CREATE TABLE IF NOT EXISTS `aditivos_nutritivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `formula_quimica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aditivos_nutritivos_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aditivos_nutritivos_picole` ;

CREATE TABLE IF NOT EXISTS `aditivos_nutritivos_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aditivo_nutritivo` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aditivos_nutritivos_picole_1_idx` (`id_aditivo_nutritivo` ASC) VISIBLE,
  INDEX `fk_aditivos_nutritivos_picole_2_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conservantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conservantes` ;

CREATE TABLE IF NOT EXISTS `conservantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conservantes_picoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conservantes_picoles` ;

CREATE TABLE IF NOT EXISTS `conservantes_picoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_conservante` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conservantes_picoles_1_idx` (`id_conservante` ASC) VISIBLE,
  INDEX `fk_conservantes_picoles_2_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lotes` ;

CREATE TABLE IF NOT EXISTS `lotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_picole` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lotes_1_idx` (`id_tipo_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revendedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `revendedores` ;

CREATE TABLE IF NOT EXISTS `revendedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `contato` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_fiscais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notas_fiscais` ;

CREATE TABLE IF NOT EXISTS `notas_fiscais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `numero_serie` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `id_revendedor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notas_fiscais_1_idx` (`id_revendedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lotes_nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lotes_nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `lotes_nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_lote` INT NOT NULL,
  `id_nota_fiscal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lotes_nota_fiscal_1_idx` (`id_lote` ASC) VISIBLE,
  INDEX `fk_lotes_nota_fiscal_2_idx` (`id_nota_fiscal` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
