-- MySQL Script generated by MySQL Workbench
-- Wed 01 Dec 2021 12:20:36 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nota_fiscal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nota_fiscal` ;

-- -----------------------------------------------------
-- Schema nota_fiscal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nota_fiscal` ;
USE `nota_fiscal` ;

-- -----------------------------------------------------
-- Table `nota_fiscal`.`nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal`.`nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `nota_fiscal`.`nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal`.`produtos` ;

CREATE TABLE IF NOT EXISTS `nota_fiscal`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descriminacao` VARCHAR(45) NOT NULL,
  `valor_unitario` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal`.`clientes` ;

CREATE TABLE IF NOT EXISTS `nota_fiscal`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `fone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`nota_fiscais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal`.`nota_fiscais` ;

CREATE TABLE IF NOT EXISTS `nota_fiscal`.`nota_fiscais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emissao` DATE NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nota_fiscais_1_idx` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`produtos_nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal`.`produtos_nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `nota_fiscal`.`produtos_nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_nota_fiscal` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_nota_fiscal_1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_produtos_nota_fiscal_2_idx` (`id_nota_fiscal` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
