-- MySQL Script generated by MySQL Workbench
-- Wed 01 Dec 2021 12:48:17 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercicio1_picoles
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exercicio1_picoles` ;

-- -----------------------------------------------------
-- Schema exercicio1_picoles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercicio1_picoles` DEFAULT CHARACTER SET utf8 ;
USE `exercicio1_picoles` ;

-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`sabores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`sabores` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`sabores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`tipo_embalagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`tipo_embalagem` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`tipo_embalagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`tipos_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`tipos_picole` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`tipos_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`picoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`picoles` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`picoles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_sabor` INT NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `id_tipo_embalagem` INT NOT NULL,
  `id_tipo_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picoles_1_idx` (`id_sabor` ASC) VISIBLE,
  INDEX `fk_picoles_2_idx` (`id_tipo_embalagem` ASC) VISIBLE,
  INDEX `fk_picole_3_idx` (`id_tipo_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`ingredientes_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`ingredientes_picole` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`ingredientes_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ingrediente` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredientes_picoles_idx` (`id_ingrediente` ASC) VISIBLE,
  INDEX `fk_id_picole_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`aditivos_nutritivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`aditivos_nutritivos` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`aditivos_nutritivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `formula_quimica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`conservantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`conservantes` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`conservantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`aditivos_nutritivos_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`aditivos_nutritivos_picole` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`aditivos_nutritivos_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aditivo_nutritivo` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_aditivo_nutritivo_idx` (`id_aditivo_nutritivo` ASC) VISIBLE,
  INDEX `fk_id_picole_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`conservantes_picole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`conservantes_picole` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`conservantes_picole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_conservante` INT NOT NULL,
  `id_picole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_conservante_idx` (`id_conservante` ASC) VISIBLE,
  INDEX `fk_id_picole_idx` (`id_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`lotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`lotes` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`lotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_picole` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lotes_idx` (`id_tipo_picole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`revendedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`revendedores` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`revendedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `contato` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `numero_serie` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `id_revendedor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_revendedor_idx` (`id_revendedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1_picoles`.`lotes_nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercicio1_picoles`.`lotes_nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `exercicio1_picoles`.`lotes_nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_lote` INT NOT NULL,
  `id_nota_fiscal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_nota_fiscal_idx` (`id_nota_fiscal` ASC) VISIBLE,
  INDEX `fk_id_lote_idx` (`id_lote` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
